### PR TITLE
remove console log for debug mode, update package version

### PR DESCRIPTION
**Pull request by VoloshchenkoAl**

### CODE REVIEW

**Comment by zeusdeux** [comment]
LGTM. One nit, could you commit using the email that connects to your GitHub account please? 
That way, it'll attribute it to you. ^_^

Also, could you please rebase with `master`. I have added a tiny action to run the build on commit pushes. That should sort the "Some checks haven't completed yet" message.

**Review by zeusdeux — CHANGES_REQUESTED** [review]
Changes requested in the comment above.

**Comment by VoloshchenkoAl** [comment]
Rebase branch with master -> done.

Hmmm, I have made all my commits with my GitHub email.

**Review by zeusdeux — APPROVED** [review]

**Comment by zeusdeux** [comment]
Thanks for this! Landed in 83bca31 and will go out with the new patch release.

**Pull request merged**
